# @see https://tester.nette.org/cs/testing-with-travis

language: php

php:
  - 5.4
  - 8.1

env:
  - TESTER_PHP_BIN="php"

before_install:
  - composer self-update

install:
  - composer update --dev

script:
  - ./vendor/bin/tester -p $TESTER_PHP_BIN -s -c ./tests/php.ini ./tests

after_failure:
  # Vytiskne obsah souborů *.actual
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done